//
//  main.m
//  ATProperties
//
//  Created by Student P_07 on 01/09/16.
//  Copyright © 2016 Aashish Tamsya. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "Vehicle.h"
#import "Bike.h"


int main(int argc, const char * argv[]) {
    @autoreleasepool {
       
        
        Vehicle *normalVehicle = [[Vehicle alloc]init];
        
        //  Setter method which is automatically generated by xcode
        [normalVehicle setOwnerName:@"Ritu"];
        
        //  Getter which is automatically generated by xcode
        NSLog(@"%@",normalVehicle.ownerName);
        

        Bike *yamaha = [[Bike alloc]init];
        
        [yamaha setLicenseNumber:@"mh-12-as-1231"];
        
        NSLog(@"Bike License : %@",yamaha.licenseNumber);
        
        yamaha.licenseNumber = @"mh-01-aq-9876";
        
        NSLog(@"Bike License : %@",yamaha.licenseNumber);

        
    }
    return 0;
}
